### ISSUE TITLE
Bottom sidebar appears while scrolling down

### ISSUE THREAD

**Issue by bkroggel** [jillix/jQuery-sidebar#22] opened 2015-07-19 12:50 UTC
I noticed a little bug opening my side on chrome for Android but I am not 100% sure that this isn't my fault. Chroms Searchbox disappears while scrolling down and shows up again while scolling up, which is totally the normal behavior of this mobile browser. The problem is that whenever I scroll down on my page and the searchbox disappears, a part of my sidebar (a bottom version) shows up on the bottom of my screen.
Using `height: xy%` instead of `px` in my `.sidebar.bottom` class causes this little bug, but the fact that opening the sidebar and closing it seems to fix this error (until i reload the site of course) makes me wonder if there might be a solution to change the experience in a simple way.

I attached two screenshots. First shows the normal view after loading the webpage. The second presents the bug at the bottom of the screen.

![at_start](https://cloud.githubusercontent.com/assets/11707221/8765929/f5205b64-2e24-11e5-91f6-48d974d1bacc.jpg)

![while_scrolling_down](https://cloud.githubusercontent.com/assets/11707221/8765936/060df7f6-2e25-11e5-8b07-444641fbba04.jpg)

**Comment by IonicaBizau** [comment] 2015-07-19 16:35
Thank you for the report, @bkroggel!

Could you please share the code via a JSBin or so (preferably a static page to reproduce the bug)? 

Personally, I cannot test this because I don't have any Android device (I don't even have a smartphone, lol :smile:), but I'm /cc-ing @silviubogan, @gabipetrovay and @lcristianiim -- maybe they have some ideas.

Btw, if you find any solution, make sure you leave a comment here as well. :sparkles:

**Comment by lcristianiim** [comment] 2015-07-19 16:53
@IonicaBizau we must get ourselves android devices, for debugging purposes :smile:

**Comment by bkroggel** [comment] 2015-07-19 19:23
Hey @IonicaBizau, thank you so much for your fast answer.

I uploaded a very basic version of my actual project to [bitballon](http://jquery-sidebar-issue22.bitballoon.com/), which might be a good solution to just throw a link up on a device.

http://jquery-sidebar-issue22.bitballoon.com/

The [jsbin](https://jsbin.com/refoqi/1/edit?html,css,js,output) is a little bit different from the bitballoon version as it won't be useful to upload my custom fonts.

https://jsbin.com/refoqi/1/edit?html,css,js,output

Both version do show the same little bug.

As I mentioned before, this bug just occurs if I use percent expressions for the height of the sidebar. Of course, I could avoid doing this as a workaround for my use case, but it just feels natural to say it should cover 100% of the screen.

I am not that much into jQuery yet, so it might be a real surprise if I find a solution by myself, but, as I am a Android user, feel free to reach out to me if you need somebody to test some modifications.

**Comment by IonicaBizau** [comment] 2015-07-19 19:33
Just to verify, the following behavior is correct, right? I tested it using the Chromium dev tools:

![out](https://cloud.githubusercontent.com/assets/2864371/8767440/af60a25a-2e65-11e5-9b06-3b943d79f2c0.gif)

I wonder if the Android browser triggers the `resize` event when the search box disappears (can you check this $(window).on("resize", console.log.bind(console, "Resize was triggered!"))`?) -- if so, this is just another effect of #19. We just have to listen to the resize event and *do something* (probably just update the sliders positions). :four_leaf_clover:

**Comment by lcristianiim** [comment] 2015-07-19 19:50
@bkroggel @IonicaBizau 
I have tested it on an ipad and there is no issue whatsoever.
When loading the page, the bottom sidebar is not displayed at all, even if I scroll till the bottom of the page.

When I click on the link with the .icon-chat, the black bottom sidebar appears full screen; right scroll bar for the page not visible at all.
While the black sidebar full screen active, if I scroll, after closing the sidebar, I can see the effect of the scroll on the page.

**Comment by lcristianiim** [comment] 2015-07-19 19:56
@bkroggel  did you tried instead of height: 100%, `height: 100vh` ?

**Comment by bkroggel** [comment] 2015-07-19 20:00
@IonicaBizau Yep, you are right, that behavior is what I wanted to see. And yeah, I took a look at the Remote Debugging Console for Android and the resize effect seems to cause this problem.

The first pic is the "before scrolling view".
![before](https://cloud.githubusercontent.com/assets/11707221/8767556/d1a2aaf2-2e60-11e5-98b3-31257572d709.jpg)

As you can see, it looks like there is a missing part of the sceen, while on the next picture the whole screen is covered (and the sidebar appears).

![after](https://cloud.githubusercontent.com/assets/11707221/8767587/5a949320-2e61-11e5-8068-7af55bfdc18b.jpg)

**Comment by bkroggel** [comment] 2015-07-19 20:07
@lcristianiim I am sorry, as far as I can see that doesn't change anything.

**Comment by IonicaBizau** [comment] 2015-07-20 04:18
@bkroggel OK, so the resize is triggered -- which is cool! I'm assigning this to me and will solve it today, I hope. We have the same problem in one of our internal apps. :smile:

**Comment by IonicaBizau** [comment] 2015-07-20 06:53
@bkroggel Could you please check out #23? I pushed a fix. I [updated the JSBin](https://jsbin.com/zavacobegu/edit?html,css,js,output) page and did the following:

 - resize the browser vertically (unmaximize)
 - open sidebar
 - close sidebar
 - maximize the browser window

In the old version the sidebar would appear on the bottom side, now it doesn't. I killed it with :fire:. :smile:

**Comment by bkroggel** [comment] 2015-07-20 08:03
That was very impressive @IonicaBizau. This issue exists for not even 24 hours and you already fixed it! :tada: :sparkles:
Looking forward to use this Sidebar in many future products...it's simple...looks really nice...works smooth...and the developers are awesome :wink:.

**Closed** 2015-07-20 08:06 UTC
Labels: bug

**Comment by IonicaBizau** [comment] 2015-07-20 08:09
@bkroggel Thank you for kind words and thank you for following me. :cake: 

I'm glad this module is useful for the people. I always liked small modules that do one thing at the time. :smile_cat: 

:ship: `3.3.0`
